export const countries = [
	{ name: 'Afghanistan', dial_code: '+93', flag: '🇦🇫', country_code: 'AF' },
	{ name: 'Albania', dial_code: '+355', flag: '🇦🇱', country_code: 'AL' },
	{ name: 'Algeria', dial_code: '+213', flag: '🇩🇿', country_code: 'DZ' },
	{ name: 'Andorra', dial_code: '+376', flag: '🇦🇩', country_code: 'AD' },
	{ name: 'Angola', dial_code: '+244', flag: '🇦🇴', country_code: 'AO' },
	{ name: 'Argentina', dial_code: '+54', flag: '🇦🇷', country_code: 'AR' },
	{ name: 'Armenia', dial_code: '+374', flag: '🇦🇲', country_code: 'AM' },
	{ name: 'Australia', dial_code: '+61', flag: '🇦🇺', country_code: 'AU' },
	{ name: 'Austria', dial_code: '+43', flag: '🇦🇹', country_code: 'AT' },
	{ name: 'Azerbaijan', dial_code: '+994', flag: '🇦🇿', country_code: 'AZ' },
	{ name: 'Bahamas', dial_code: '+1-242', flag: '🇧🇸', country_code: 'BS' },
	{ name: 'Bahrain', dial_code: '+973', flag: '🇧🇭', country_code: 'BH' },
	{ name: 'Bangladesh', dial_code: '+880', flag: '🇧🇩', country_code: 'BD' },
	{ name: 'Barbados', dial_code: '+1-246', flag: '🇧🇧', country_code: 'BB' },
	{ name: 'Belarus', dial_code: '+375', flag: '🇧🇾', country_code: 'BY' },
	{ name: 'Belgium', dial_code: '+32', flag: '🇧🇪', country_code: 'BE' },
	{ name: 'Belize', dial_code: '+501', flag: '🇧🇿', country_code: 'BZ' },
	{ name: 'Benin', dial_code: '+229', flag: '🇧🇯', country_code: 'BJ' },
	{ name: 'Bhutan', dial_code: '+975', flag: '🇧🇹', country_code: 'BT' },
	{ name: 'Bolivia', dial_code: '+591', flag: '🇧🇴', country_code: 'BO' },
	{ name: 'Bosnia and Herzegovina', dial_code: '+387', flag: '🇧🇦', country_code: 'BA' },
	{ name: 'Botswana', dial_code: '+267', flag: '🇧🇼', country_code: 'BW' },
	{ name: 'Brazil', dial_code: '+55', flag: '🇧🇷', country_code: 'BR' },
	{ name: 'Brunei', dial_code: '+673', flag: '🇧🇳', country_code: 'BN' },
	{ name: 'Bulgaria', dial_code: '+359', flag: '🇧🇬', country_code: 'BG' },
	{ name: 'Burkina Faso', dial_code: '+226', flag: '🇧🇫', country_code: 'BF' },
	{ name: 'Burundi', dial_code: '+257', flag: '🇧🇮', country_code: 'BI' },
	{ name: 'Cambodia', dial_code: '+855', flag: '🇰🇭', country_code: 'KH' },
	{ name: 'Cameroon', dial_code: '+237', flag: '🇨🇲', country_code: 'CM' },
	{ name: 'Canada', dial_code: '+1', flag: '🇨🇦', country_code: 'CA' },
	{ name: 'Cape Verde', dial_code: '+238', flag: '🇨🇻', country_code: 'CV' },
	{ name: 'Central African Republic', dial_code: '+236', flag: '🇨🇫', country_code: 'CF' },
	{ name: 'Chad', dial_code: '+235', flag: '🇹🇩', country_code: 'TD' },
	{ name: 'Chile', dial_code: '+56', flag: '🇨🇱', country_code: 'CL' },
	{ name: 'China', dial_code: '+86', flag: '🇨🇳', country_code: 'CN' },
	{ name: 'Colombia', dial_code: '+57', flag: '🇨🇴', country_code: 'CO' },
	{ name: 'Comoros', dial_code: '+269', flag: '🇰🇲', country_code: 'KM' },
	{ name: 'Congo', dial_code: '+242', flag: '🇨🇬', country_code: 'CG' },
	{ name: 'Congo (Democratic Republic)', dial_code: '+243', flag: '🇨🇩', country_code: 'CD' },
	{ name: 'Costa Rica', dial_code: '+506', flag: '🇨🇷', country_code: 'CR' },
	{ name: 'Croatia', dial_code: '+385', flag: '🇭🇷', country_code: 'HR' },
	{ name: 'Cuba', dial_code: '+53', flag: '🇨🇺', country_code: 'CU' },
	{ name: 'Cyprus', dial_code: '+357', flag: '🇨🇾', country_code: 'CY' },
	{ name: 'Czech Republic', dial_code: '+420', flag: '🇨🇿', country_code: 'CZ' },
	{ name: 'Denmark', dial_code: '+45', flag: '🇩🇰', country_code: 'DK' },
	{ name: 'Djibouti', dial_code: '+253', flag: '🇩🇯', country_code: 'DJ' },
	{ name: 'Dominica', dial_code: '+1-767', flag: '🇩🇲', country_code: 'DM' },
	{ name: 'Dominican Republic', dial_code: '+1-809', flag: '🇩🇴', country_code: 'DO' },
	{ name: 'East Timor', dial_code: '+670', flag: '🇹🇱', country_code: 'TL' },
	{ name: 'Ecuador', dial_code: '+593', flag: '🇪🇨', country_code: 'EC' },
	{ name: 'Egypt', dial_code: '+20', flag: '🇪🇬', country_code: 'EG' },
	{ name: 'El Salvador', dial_code: '+503', flag: '🇸🇻', country_code: 'SV' },
	{ name: 'Equatorial Guinea', dial_code: '+240', flag: '🇬🇶', country_code: 'GQ' },
	{ name: 'Eritrea', dial_code: '+291', flag: '🇪🇷', country_code: 'ER' },
	{ name: 'Estonia', dial_code: '+372', flag: '🇪🇪', country_code: 'EE' },
	{ name: 'Eswatini', dial_code: '+268', flag: '🇸🇿', country_code: 'SZ' },
	{ name: 'Ethiopia', dial_code: '+251', flag: '🇪🇹', country_code: 'ET' },
	{ name: 'Fiji', dial_code: '+679', flag: '🇫🇯', country_code: 'FJ' },
	{ name: 'Finland', dial_code: '+358', flag: '🇫🇮', country_code: 'FI' },
	{ name: 'France', dial_code: '+33', flag: '🇫🇷', country_code: 'FR' },
	{ name: 'Gabon', dial_code: '+241', flag: '🇬🇦', country_code: 'GA' },
	{ name: 'Gambia', dial_code: '+220', flag: '🇬🇲', country_code: 'GM' },
	{ name: 'Georgia', dial_code: '+995', flag: '🇬🇪', country_code: 'GE' },
	{ name: 'Germany', dial_code: '+49', flag: '🇩🇪', country_code: 'DE' },
	{ name: 'Ghana', dial_code: '+233', flag: '🇬🇭', country_code: 'GH' },
	{ name: 'Greece', dial_code: '+30', flag: '🇬🇷', country_code: 'GR' },
	{ name: 'Grenada', dial_code: '+1-473', flag: '🇬🇩', country_code: 'GD' },
	{ name: 'Guatemala', dial_code: '+502', flag: '🇬🇹', country_code: 'GT' },
	{ name: 'Guinea', dial_code: '+224', flag: '🇬🇳', country_code: 'GN' },
	{ name: 'Guinea-Bissau', dial_code: '+245', flag: '🇬🇼', country_code: 'GW' },
	{ name: 'Guyana', dial_code: '+592', flag: '🇬🇾', country_code: 'GY' },
	{ name: 'Haiti', dial_code: '+509', flag: '🇭🇹', country_code: 'HT' },
	{ name: 'Honduras', dial_code: '+504', flag: '🇭🇳', country_code: 'HN' },
	{ name: 'Hungary', dial_code: '+36', flag: '🇭🇺', country_code: 'HU' },
	{ name: 'Iceland', dial_code: '+354', flag: '🇮🇸', country_code: 'IS' },
	{ name: 'India', dial_code: '+91', flag: '🇮🇳', country_code: 'IN' },
	{ name: 'Indonesia', dial_code: '+62', flag: '🇮🇩', country_code: 'ID' },
	{ name: 'Iran', dial_code: '+98', flag: '🇮🇷', country_code: 'IR' },
	{ name: 'Iraq', dial_code: '+964', flag: '🇮🇶', country_code: 'IQ' },
	{ name: 'Ireland', dial_code: '+353', flag: '🇮🇪', country_code: 'IE' },
	{ name: 'Israel', dial_code: '+972', flag: '🇮🇱', country_code: 'IL' },
	{ name: 'Italy', dial_code: '+39', flag: '🇮🇹', country_code: 'IT' },
	{ name: 'Ivory Coast', dial_code: '+225', flag: '🇨🇮', country_code: 'CI' },
	{ name: 'Jamaica', dial_code: '+1-876', flag: '🇯🇲', country_code: 'JM' },
	{ name: 'Japan', dial_code: '+81', flag: '🇯🇵', country_code: 'JP' },
	{ name: 'Jordan', dial_code: '+962', flag: '🇯🇴', country_code: 'JO' },
	{ name: 'Kazakhstan', dial_code: '+7', flag: '🇰🇿', country_code: 'KZ' },
	{ name: 'Kenya', dial_code: '+254', flag: '🇰🇪', country_code: 'KE' },
	{ name: 'Kiribati', dial_code: '+686', flag: '🇰🇮', country_code: 'KI' },
	{ name: 'Kuwait', dial_code: '+965', flag: '🇰🇼', country_code: 'KW' },
	{ name: 'Kyrgyzstan', dial_code: '+996', flag: '🇰🇬', country_code: 'KG' },
	{ name: 'Laos', dial_code: '+856', flag: '🇱🇦', country_code: 'LA' },
	{ name: 'Latvia', dial_code: '+371', flag: '🇱🇻', country_code: 'LV' },
	{ name: 'Lebanon', dial_code: '+961', flag: '🇱🇧', country_code: 'LB' },
	{ name: 'Lesotho', dial_code: '+266', flag: '🇱🇸', country_code: 'LS' },
	{ name: 'Liberia', dial_code: '+231', flag: '🇱🇷', country_code: 'LR' },
	{ name: 'Libya', dial_code: '+218', flag: '🇱🇾', country_code: 'LY' },
	{ name: 'Liechtenstein', dial_code: '+423', flag: '🇱🇮', country_code: 'LI' },
	{ name: 'Lithuania', dial_code: '+370', flag: '🇱🇹', country_code: 'LT' },
	{ name: 'Luxembourg', dial_code: '+352', flag: '🇱🇺', country_code: 'LU' },
	{ name: 'Madagascar', dial_code: '+261', flag: '🇲🇬', country_code: 'MG' },
	{ name: 'Malawi', dial_code: '+265', flag: '🇲🇼', country_code: 'MW' },
	{ name: 'Malaysia', dial_code: '+60', flag: '🇲🇾', country_code: 'MY' },
	{ name: 'Maldives', dial_code: '+960', flag: '🇲🇻', country_code: 'MV' },
	{ name: 'Mali', dial_code: '+223', flag: '🇲🇱', country_code: 'ML' },
	{ name: 'Malta', dial_code: '+356', flag: '🇲🇹', country_code: 'MT' },
	{ name: 'Marshall Islands', dial_code: '+692', flag: '🇲🇭', country_code: 'MH' },
	{ name: 'Mauritania', dial_code: '+222', flag: '🇲🇷', country_code: 'MR' },
	{ name: 'Mauritius', dial_code: '+230', flag: '🇲🇺', country_code: 'MU' },
	{ name: 'Mexico', dial_code: '+52', flag: '🇲🇽', country_code: 'MX' },
	{ name: 'Micronesia', dial_code: '+691', flag: '🇫🇲', country_code: 'FM' },
	{ name: 'Moldova', dial_code: '+373', flag: '🇲🇩', country_code: 'MD' },
	{ name: 'Monaco', dial_code: '+377', flag: '🇲🇨', country_code: 'MC' },
	{ name: 'Mongolia', dial_code: '+976', flag: '🇲🇳', country_code: 'MN' },
	{ name: 'Montenegro', dial_code: '+382', flag: '🇲🇪', country_code: 'ME' },
	{ name: 'Morocco', dial_code: '+212', flag: '🇲🇦', country_code: 'MA' },
	{ name: 'Mozambique', dial_code: '+258', flag: '🇲🇿', country_code: 'MZ' },
	{ name: 'Myanmar', dial_code: '+95', flag: '🇲🇲', country_code: 'MM' },
	{ name: 'Namibia', dial_code: '+264', flag: '🇳🇦', country_code: 'NA' },
	{ name: 'Nauru', dial_code: '+674', flag: '🇳🇷', country_code: 'NR' },
	{ name: 'Nepal', dial_code: '+977', flag: '🇳🇵', country_code: 'NP' },
	{ name: 'Netherlands', dial_code: '+31', flag: '🇳🇱', country_code: 'NL' },
	{ name: 'New Zealand', dial_code: '+64', flag: '🇳🇿', country_code: 'NZ' },
	{ name: 'Nicaragua', dial_code: '+505', flag: '🇳🇮', country_code: 'NI' },
	{ name: 'Niger', dial_code: '+227', flag: '🇳🇪', country_code: 'NE' },
	{ name: 'Nigeria', dial_code: '+234', flag: '🇳🇬', country_code: 'NG' },
	{ name: 'North Korea', dial_code: '+850', flag: '🇰🇵', country_code: 'KP' },
	{ name: 'North Macedonia', dial_code: '+389', flag: '🇲🇰', country_code: 'MK' },
	{ name: 'Norway', dial_code: '+47', flag: '🇳🇴', country_code: 'NO' },
	{ name: 'Oman', dial_code: '+968', flag: '🇴🇲', country_code: 'OM' },
	{ name: 'Pakistan', dial_code: '+92', flag: '🇵🇰', country_code: 'PK' },
	{ name: 'Palau', dial_code: '+680', flag: '🇵🇼', country_code: 'PW' },
	{ name: 'Panama', dial_code: '+507', flag: '🇵🇦', country_code: 'PA' },
	{ name: 'Papua New Guinea', dial_code: '+675', flag: '🇵🇬', country_code: 'PG' },
	{ name: 'Paraguay', dial_code: '+595', flag: '🇵🇾', country_code: 'PY' },
	{ name: 'Peru', dial_code: '+51', flag: '🇵🇪', country_code: 'PE' },
	{ name: 'Philippines', dial_code: '+63', flag: '🇵🇭', country_code: 'PH' },
	{ name: 'Poland', dial_code: '+48', flag: '🇵🇱', country_code: 'PL' },
	{ name: 'Portugal', dial_code: '+351', flag: '🇵🇹', country_code: 'PT' },
	{ name: 'Qatar', dial_code: '+974', flag: '🇶🇦', country_code: 'QA' },
	{ name: 'Romania', dial_code: '+40', flag: '🇷🇴', country_code: 'RO' },
	{ name: 'Russia', dial_code: '+7', flag: '🇷🇺', country_code: 'RU' },
	{ name: 'Rwanda', dial_code: '+250', flag: '🇷🇼', country_code: 'RW' },
	{ name: 'Saint Kitts and Nevis', dial_code: '+1-869', flag: '🇰🇳', country_code: 'KN' },
	{ name: 'Saint Lucia', dial_code: '+1-758', flag: '🇱🇨', country_code: 'LC' },
	{ name: 'Saint Vincent and the Grenadines', dial_code: '+1-784', flag: '🇻🇨', country_code: 'VC' },
	{ name: 'Samoa', dial_code: '+685', flag: '🇼🇸', country_code: 'WS' },
	{ name: 'San Marino', dial_code: '+378', flag: '🇸🇲', country_code: 'SM' },
	{ name: 'Sao Tome and Principe', dial_code: '+239', flag: '🇸🇹', country_code: 'ST' },
	{ name: 'Saudi Arabia', dial_code: '+966', flag: '🇸🇦', country_code: 'SA' },
	{ name: 'Senegal', dial_code: '+221', flag: '🇸🇳', country_code: 'SN' },
	{ name: 'Serbia', dial_code: '+381', flag: '🇷🇸', country_code: 'RS' },
	{ name: 'Seychelles', dial_code: '+248', flag: '🇸🇨', country_code: 'SC' },
	{ name: 'Sierra Leone', dial_code: '+232', flag: '🇸🇱', country_code: 'SL' },
	{ name: 'Singapore', dial_code: '+65', flag: '🇸🇬', country_code: 'SG' },
	{ name: 'Slovakia', dial_code: '+421', flag: '🇸🇰', country_code: 'SK' },
	{ name: 'Slovenia', dial_code: '+386', flag: '🇸🇮', country_code: 'SI' },
	{ name: 'Solomon Islands', dial_code: '+677', flag: '🇸🇧', country_code: 'SB' },
	{ name: 'Somalia', dial_code: '+252', flag: '🇸🇴', country_code: 'SO' },
	{ name: 'South Africa', dial_code: '+27', flag: '🇿🇦', country_code: 'ZA' },
	{ name: 'South Korea', dial_code: '+82', flag: '🇰🇷', country_code: 'KR' },
	{ name: 'South Sudan', dial_code: '+211', flag: '🇸🇸', country_code: 'SS' },
	{ name: 'Spain', dial_code: '+34', flag: '🇪🇸', country_code: 'ES' },
	{ name: 'Sri Lanka', dial_code: '+94', flag: '🇱🇰', country_code: 'LK' },
	{ name: 'Sudan', dial_code: '+249', flag: '🇸🇩', country_code: 'SD' },
	{ name: 'Suriname', dial_code: '+597', flag: '🇸🇷', country_code: 'SR' },
	{ name: 'Sweden', dial_code: '+46', flag: '🇸🇪', country_code: 'SE' },
	{ name: 'Switzerland', dial_code: '+41', flag: '🇨🇭', country_code: 'CH' },
	{ name: 'Syria', dial_code: '+963', flag: '🇸🇾', country_code: 'SY' },
	{ name: 'Taiwan', dial_code: '+886', flag: '🇹🇼', country_code: 'TW' },
	{ name: 'Tajikistan', dial_code: '+992', flag: '🇹🇯', country_code: 'TJ' },
	{ name: 'Tanzania', dial_code: '+255', flag: '🇹🇿', country_code: 'TZ' },
	{ name: 'Thailand', dial_code: '+66', flag: '🇹🇭', country_code: 'TH' },
	{ name: 'Togo', dial_code: '+228', flag: '🇹🇬', country_code: 'TG' },
	{ name: 'Tonga', dial_code: '+676', flag: '🇹🇴', country_code: 'TO' },
	{ name: 'Trinidad and Tobago', dial_code: '+1-868', flag: '🇹🇹', country_code: 'TT' },
	{ name: 'Tunisia', dial_code: '+216', flag: '🇹🇳', country_code: 'TN' },
	{ name: 'Turkey', dial_code: '+90', flag: '🇹🇷', country_code: 'TR' },
	{ name: 'Turkmenistan', dial_code: '+993', flag: '🇹🇲', country_code: 'TM' },
	{ name: 'Tuvalu', dial_code: '+688', flag: '🇹🇻', country_code: 'TV' },
	{ name: 'Uganda', dial_code: '+256', flag: '🇺🇬', country_code: 'UG' },
	{ name: 'Ukraine', dial_code: '+380', flag: '🇺🇦', country_code: 'UA' },
	{ name: 'United Arab Emirates', dial_code: '+971', flag: '🇦🇪', country_code: 'AE' },
	{ name: 'United Kingdom', dial_code: '+44', flag: '🇬🇧', country_code: 'GB' },
	{ name: 'United States', dial_code: '+1', flag: '🇺🇸', country_code: 'US' },
	{ name: 'Uruguay', dial_code: '+598', flag: '🇺🇾', country_code: 'UY' },
	{ name: 'Uzbekistan', dial_code: '+998', flag: '🇺🇿', country_code: 'UZ' },
	{ name: 'Vanuatu', dial_code: '+678', flag: '🇻🇺', country_code: 'VU' },
	{ name: 'Vatican City', dial_code: '+379', flag: '🇻🇦', country_code: 'VA' },
	{ name: 'Venezuela', dial_code: '+58', flag: '🇻🇪', country_code: 'VE' },
	{ name: 'Vietnam', dial_code: '+84', flag: '🇻🇳', country_code: 'VN' },
	{ name: 'Yemen', dial_code: '+967', flag: '🇾🇪', country_code: 'YE' },
	{ name: 'Zambia', dial_code: '+260', flag: '🇿🇲', country_code: 'ZM' },
	{ name: 'Zimbabwe', dial_code: '+263', flag: '🇿🇼', country_code: 'ZW' },
];
