name: SonarCloud

on:
    push:
        branches: [main]
    pull_request:
        branches: [main]

jobs:
    build:
        name: SonarCloud Scan
        runs-on: ubuntu-latest

        steps:
            - name: Checkout repository
              uses: actions/checkout@v3

            - name: Setup Node.js
              uses: actions/setup-node@v3
              with:
                  node-version: 22

            - name: Install dependencies
              run: yarn install

            - name: Build project
              run: yarn build

            - name: Run tests and generate coverage
              run: yarn test --coverage

            - name: SonarCloud Scan
              uses: SonarSource/sonarcloud-github-action@v2
              with:
                  projectBaseDir: .
              env:
                  SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
